name: rendezvous
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 4.42.0+6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flutter_svg: ^0.20.0-nullsafety.3
  flutter_spinkit: ^5.1.0
  cached_network_image: ^3.2.0
  http: ^0.13.3
  path_provider: ^2.0.4
  shimmer: ^2.0.0
  url_launcher: ^6.0.10
  share: ^2.0.4
  animated_text_kit: ^4.2.1
  # qr_code_dart_scan: 
  qr_code_scanner:
  # twitter_qr_scanner:
  image: ^3.1.0
  pie_chart: ^5.1.0
  webview_flutter: ^2.0.13
  get: 4.3.8
  hive:
  hive_flutter:
  lottie:
  qr_flutter:
  firebase_messaging:
  firebase_core:
  razorpay_flutter:
  video_360:
  youtube_player_flutter:
  dio:

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/svg/
    - assets/lottie/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
      - family: Montserrat
        fonts:
            - asset: assets/fonts/Montserrat-Medium.ttf
            - asset: assets/fonts/Montserrat-Regular.ttf
      - family: Merriweather
        fonts:
            - asset: assets/fonts/Merriweather-Regular.ttf
            - asset: assets/fonts/Merriweather-Black.ttf